// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Models.Models
{
    public partial class AsignacionEmpleados
    {
        public int AsignacionID { get; set; }
        public int? EmpleadoID { get; set; }
        public int? TiendaID { get; set; }
        public DateTime Fecha { get; set; }

        public virtual Empleados Empleado { get; set; }
        public virtual Tiendas Tienda { get; set; }
    }
}