// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Models.Models
{
    public partial class Empleados
    {
        public Empleados()
        {
            AsignacionEmpleados = new HashSet<AsignacionEmpleados>();
            InverseSupervisor = new HashSet<Empleados>();
        }

        public int EmpleadoID { get; set; }
        public string Nombre { get; set; }
        public int? UsuarioID { get; set; }
        public int? PerfilID { get; set; }
        public int? SupervisorID { get; set; }
        public string Telefono { get; set; }
        public DateTime? Fecha { get; set; }
        public string TipoEmpleado { get; set; }
        public decimal? Salario { get; set; }

        public virtual Perfil Perfil { get; set; }
        public virtual Empleados Supervisor { get; set; }
        public virtual Usuarios Usuario { get; set; }
        public virtual ICollection<AsignacionEmpleados> AsignacionEmpleados { get; set; }
        public virtual ICollection<Empleados> InverseSupervisor { get; set; }
    }
}