// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Prueba.Models.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Prueba.Models.Models
{
    public partial interface IP1700ContextProcedures
    {
        Task<List<ObtenerCantidadEmpleadosSupervisadosResult>> ObtenerCantidadEmpleadosSupervisadosAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ObtenerEmpleadosResult>> ObtenerEmpleadosAsync(string Cedula, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
