// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Prueba.Models.Models
{
    public partial class ObtenerEmpleadosResult
    {
        public string NombreEmpleado { get; set; }
        public string Telefono { get; set; }
        public DateTime? Fecha { get; set; }
        public string TipoEmpleado { get; set; }
        [Column("Salario", TypeName = "decimal(10,2)")]
        public decimal? Salario { get; set; }
        public string NombreSupervisor { get; set; }
    }
}
