// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Prueba.Models.Models
{
    public partial class P1700Context : DbContext
    {
        public P1700Context()
        {
        }

        public P1700Context(DbContextOptions<P1700Context> options)
            : base(options)
        {
        }

        public virtual DbSet<AsignacionEmpleados> AsignacionEmpleados { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Tiendas> Tiendas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer(StringConexion.ConexionSQL);

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AsignacionEmpleados>(entity =>
            {
                entity.HasKey(e => e.AsignacionID)
                    .HasName("PK__Asignaci__D82B5BB773F9800C");

                entity.HasIndex(e => new { e.EmpleadoID, e.Fecha }, "UQ__Asignaci__7EBB2E54D0D00F3A")
                    .IsUnique();

                entity.Property(e => e.Fecha).HasColumnType("date");

                entity.HasOne(d => d.Empleado)
                    .WithMany(p => p.AsignacionEmpleados)
                    .HasForeignKey(d => d.EmpleadoID)
                    .HasConstraintName("FK__Asignacio__Emple__00200768");

                entity.HasOne(d => d.Tienda)
                    .WithMany(p => p.AsignacionEmpleados)
                    .HasForeignKey(d => d.TiendaID)
                    .HasConstraintName("FK__Asignacio__Tiend__01142BA1");
            });

            modelBuilder.Entity<Empleados>(entity =>
            {
                entity.HasKey(e => e.EmpleadoID)
                    .HasName("PK__Empleado__958BE6F0473252EC");

                entity.HasIndex(e => e.UsuarioID, "IX_Empleados_UsuarioID")
                    .IsUnique()
                    .HasFilter("([UsuarioID] IS NOT NULL)");

                entity.Property(e => e.Fecha).HasColumnType("date");

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Salario).HasColumnType("decimal(10, 2)");

                entity.Property(e => e.Telefono)
                    .HasMaxLength(15)
                    .IsUnicode(false);

                entity.Property(e => e.TipoEmpleado)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Perfil)
                    .WithMany(p => p.Empleados)
                    .HasForeignKey(d => d.PerfilID)
                    .HasConstraintName("FK__Empleados__Perfi__693CA210");

                entity.HasOne(d => d.Supervisor)
                    .WithMany(p => p.InverseSupervisor)
                    .HasForeignKey(d => d.SupervisorID)
                    .HasConstraintName("FK__Empleados__Super__02084FDA");

                entity.HasOne(d => d.Usuario)
                    .WithOne(p => p.Empleados)
                    .HasForeignKey<Empleados>(d => d.UsuarioID)
                    .HasConstraintName("FK__Empleados__Usuar__68487DD7");
            });

            modelBuilder.Entity<Perfil>(entity =>
            {
                entity.Property(e => e.NombrePerfil)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Permisos>(entity =>
            {
                entity.HasKey(e => e.PermisoID)
                    .HasName("PK__Permisos__96E0C7036B0BADE9");

                entity.Property(e => e.NombrePermiso)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Perfil)
                    .WithMany(p => p.Permisos)
                    .HasForeignKey(d => d.PerfilID)
                    .HasConstraintName("FK__Permisos__Perfil__6C190EBB");
            });

            modelBuilder.Entity<Tiendas>(entity =>
            {
                entity.HasKey(e => e.TiendaID)
                    .HasName("PK__Tiendas__FC84C42C81AB0787");

                entity.Property(e => e.NombreTienda)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Usuarios>(entity =>
            {
                entity.HasKey(e => e.UsuarioID)
                    .HasName("PK__Usuarios__2B3DE7983292814F");

                entity.HasIndex(e => e.Correo, "UQ__Usuarios__60695A19599A045E")
                    .IsUnique();

                entity.Property(e => e.Cedula)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Contrasena)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Correo)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            OnModelCreatingGeneratedProcedures(modelBuilder);
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}