// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Models.Models
{
    public partial class Perfil
    {
        public Perfil()
        {
            Empleados = new HashSet<Empleados>();
            Permisos = new HashSet<Permisos>();
        }

        public int PerfilID { get; set; }
        public string NombrePerfil { get; set; }

        public virtual ICollection<Empleados> Empleados { get; set; }
        public virtual ICollection<Permisos> Permisos { get; set; }
    }
}