// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Models.Models
{
    public partial class Permisos
    {
        public int PermisoID { get; set; }
        public string NombrePermiso { get; set; }
        public int? PerfilID { get; set; }

        public virtual Perfil Perfil { get; set; }
    }
}