// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prueba.Models.Models
{
    public partial class Tiendas
    {
        public Tiendas()
        {
            AsignacionEmpleados = new HashSet<AsignacionEmpleados>();
        }

        public int TiendaID { get; set; }
        public string NombreTienda { get; set; }

        public virtual ICollection<AsignacionEmpleados> AsignacionEmpleados { get; set; }
    }
}